version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  cloudwatch:
    class: log_config.CloudWatchLogHandler
    log_group: /aws/lambda/airzoneChatbotScraper
    level: DEBUG
    formatter: simple

root:
  level: DEBUG
  handlers: [console, cloudwatch]